## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key="AIzaSyChLDVkKY9X15qhimASKPISL_vzN6NzqV0")

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ushuaia,AR,-54.8000,-68.3000,35.26,87,75,0.00,broken clouds
1,1,Hermanus,ZA,-34.4187,19.2345,44.91,69,44,10.33,light rain
2,2,Buraydah,SA,26.3260,43.9750,91.85,14,5,13.58,clear sky
3,3,Avera,US,33.1940,-82.5271,77.72,90,98,4.74,overcast clouds
4,4,Kapaa,US,22.0752,-159.3190,80.92,79,75,5.01,light rain

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
#min_temp = float(input("What is the minimum temperature you would prefer for this vacation? "))

In [5]:
#max_temp = float(input("What is the maximum temperature you would like for this vacation? "))

In [3]:
min_temp = 70

In [4]:
max_temp = 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
Vacation_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
Vacation_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Avera,US,33.1940,-82.5271,77.72,90,98,4.74,overcast clouds
4,4,Kapaa,US,22.0752,-159.3190,80.92,79,75,5.01,light rain
8,8,Rikitea,PF,-23.1203,-134.9692,72.52,67,1,15.21,clear sky
11,11,Atuona,PF,-9.8000,-139.0333,77.58,68,47,15.23,scattered clouds
18,18,Butaritari,KI,3.0707,172.7902,83.12,74,20,12.28,few clouds
20,20,Encheng,CN,22.1839,112.3026,84.96,72,97,5.19,light rain
23,23,Westport,US,41.1415,-73.3579,72.75,81,1,5.99,clear sky
31,31,Namatanai,PG,-3.6667,152.4333,81.41,79,65,5.70,light rain
32,32,Salalah,OM,17.0151,54.0924,78.89,94,75,9.22,broken clouds
35,35,Buala,SB,-8.1450,159.5921,84.04,71,27,5.97,light rain

In [6]:
# 4a. Determine if there are any empty rows.
Vacation_cities_df.count()

City_ID                315
City                   315
Country                315
Lat                    315
Lng                    315
Max Temp               315
Humidity               315
Cloudiness             315
Wind Speed             315
Current Description    315
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
Vacation_cities_clean_df = Vacation_cities_df.dropna()
Vacation_cities_clean_df.count()

City_ID                315
City                   315
Country                315
Lat                    315
Lng                    315
Max Temp               315
Humidity               315
Cloudiness             315
Wind Speed             315
Current Description    315
dtype: int64

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = Vacation_cities_clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Avera,US,77.72,overcast clouds,33.1940,-82.5271,
4,Kapaa,US,80.92,light rain,22.0752,-159.3190,
8,Rikitea,PF,72.52,clear sky,-23.1203,-134.9692,
11,Atuona,PF,77.58,scattered clouds,-9.8000,-139.0333,
18,Butaritari,KI,83.12,few clouds,3.0707,172.7902,
20,Encheng,CN,84.96,light rain,22.1839,112.3026,
23,Westport,US,72.75,clear sky,41.1415,-73.3579,
31,Namatanai,PG,81.41,light rain,-3.6667,152.4333,
32,Salalah,OM,78.89,broken clouds,17.0151,54.0924,
35,Buala,SB,84.04,light rain,-8.1450,159.5921,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

In [15]:
# # 6b. Iterate through the hotel DataFrame.
for index, hotel in hotel_df.iterrows():
    
     # 6c. Get latitude and longitude from DataFrame
    
    lat = hotel["Lat"]
    lng = hotel["Lng"]
    params["location"]= f'{lat},{lng}'
    
     # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    
    hotels = requests.get(base_url, params=params).json()
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [18]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Avera,US,77.72,overcast clouds,33.1940,-82.5271,
4,Kapaa,US,80.92,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
8,Rikitea,PF,72.52,clear sky,-23.1203,-134.9692,People ThankYou
11,Atuona,PF,77.58,scattered clouds,-9.8000,-139.0333,Villa Enata
18,Butaritari,KI,83.12,few clouds,3.0707,172.7902,Isles Sunset Lodge
20,Encheng,CN,84.96,light rain,22.1839,112.3026,Pinghu Hostel
23,Westport,US,72.75,clear sky,41.1415,-73.3579,The Westport Inn
31,Namatanai,PG,81.41,light rain,-3.6667,152.4333,Seagulls Inn Namatani
32,Salalah,OM,78.89,broken clouds,17.0151,54.0924,HAMDAN PLAZA HOTEL SALALAH
35,Buala,SB,84.04,light rain,-8.1450,159.5921,Maringe Lagoon Lodge

In [27]:
# 7. Drop the rows where there is no Hotel Name.
Hotel_clean_df = hotel_df.dropna()
Hotel_clean_df.count()

City                   315
Country                315
Max Temp               315
Current Description    315
Lat                    315
Lng                    315
Hotel Name             315
dtype: int64

In [20]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
Hotel_clean_df.to_csv(output_data_file, index_label="City_ID")

In [28]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current description</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in Hotel_clean_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = Hotel_clean_df[["Lat", "Lng"]]

In [29]:
# 11a. Add a marker layer for each city to the map. 

locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))